### ISSUE TITLE
Cut a crates.io release with `queue_with_hold`

### ISSUE THREAD

**Issue by alexgenco** [mikecaines/stream-throttle#9]
Hello, just wondering if you have plans to cut a release to crates.io including the `queue_with_hold` method? I can pin to the git sha for now but would prefer a proper version. Thanks!

**Comment by mikecaines** [comment]
Yes, I can do that. I'll try and get to it over the next few days. Thanks!

**Comment by mikecaines** [comment]
@alexgenco I pushed v0.5.0

**Comment by mikecaines** [comment]
Whoops, need to push to crates.io as well. Will do that

**Comment by mikecaines** [comment]
pushed to crates.io as well
